# Generated by Django 4.2.25 on 2025-10-02 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0005_sprint_tarea_tarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='Tarea',
        ),
        migrations.AddField(
            model_name='tarea',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrum.sprint'),
        ),
    ]
